# Generated by Django 5.1 on 2024-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='/default_image.jpg', upload_to='movies/'),
        ),
    ]
